### ISSUE TITLE
Favorites bar bugged

### ISSUE THREAD

**Issue by Blobvoid** [RiceCakess/Holodex-old#23] opened 2021-01-03 05:08 UTC
The favorites bar does not show some members as live, even if the rest of the sites says they are live.

**Comment by RiceCakess** [comment] 2021-01-07 22:06
Duplicate of #22 

Could you take a screen shot of what you see when it happens?

**Comment by Blobvoid** [comment] 2021-01-10 02:04
![Screenshot 2021-01-09 190303](https://user-images.githubusercontent.com/76894427/104112548-7757e180-52ad-11eb-8393-1e0b0c93dc22.png)
sorry for the wait

**Comment by RiceCakess** [comment] 2021-01-23 12:19
still working on it in version 2, but closing this issue for now

**Closed as completed** 2021-01-23 12:18 UTC
